### ISSUE TITLE
Chrcoal CMS  not working

### ISSUE THREAD

**Issue by bidyashish** [locomotivemtl/charcoal-cms#6]
Hello , firstly I cloned this repo , then run   "composer require locomotivemtl/charcoal-cms" , i am unable to open website   or CMS system i.e Front end the go to Backend  | admin page .
Please help me out , as i m building website CMS with Charcoal CMS .
 Thanks

**Comment by mducharme** [comment]
To start with Charcoal, please start with the boilerplate: https://github.com/locomotivemtl/charcoal-project-boilerplate
